# Generated by Django 3.0 on 2019-12-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwords',
            options={'verbose_name_plural': 'Passwords'},
        ),
    ]
